name: pizzato
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.0
  # eva_icons_flutter: ^2.0.1
  # firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  firebase_core: ^0.5.2+1
  # flutter_secure_storage: ^3.3.5
  font_awesome_flutter: ^8.10.0
  # geocoder: ^0.2.1
  # geolocator: ^6.1.8
  # google_maps_flutter: ^1.0.6
  # google_sign_in: ^4.5.6
  lottie: ^0.7.0+1
  page_transition: ^1.1.7+2
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - animations/preparing-food.json


  uses-material-design: true
